### ISSUE TITLE
Feat: Indicating that a column is sortable

### ISSUE THREAD

**Issue by ofirgeller** [react-tools/react-table#567]
## What version of React-Table are you using? 
6.6.0

## Feature Request
Indicating that a column is sortable: currently the only visual indication is the cursor when hovering. The design used to indicate the current sort direction has the advantage of saving on horizontal space, however it has no distinction between the 'none but sortable' state and the 'not sorteable state'.

This works nicely for me: (LESS precompiled)

```LESS
.ReactTable .rt-thead .rt-th.-cursor-pointer,
.ReactTable .rt-thead .rt-td.-cursor-pointer {
    box-shadow: inset 0 2px 0 0 rgba(0, 0, 0, 0.1), inset 0 -2px 0 0 rgba(0, 0, 0, 0.1);
    &.-sort-asc {
        box-shadow: inset 0 3px 0 0 rgba(0, 0, 0, 0.6), inset 0 -2px 0 0 rgba(0, 0, 0, 0.1);
    }
    &.-sort-desc {
        box-shadow: inset 0 -3px 0 0 rgba(0, 0, 0, 0.6), inset 0 2px 0 0 rgba(0, 0, 0, 0.1)
    }
}
```
